USE [master]
GO
/****** Object:  Database [FoodRecipes]    Script Date: 10/6/2022 12:59:02 AM ******/
CREATE DATABASE [FoodRecipes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FoodRecipes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\FoodRecipes.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FoodRecipes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\FoodRecipes_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [FoodRecipes] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FoodRecipes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FoodRecipes] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FoodRecipes] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FoodRecipes] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FoodRecipes] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FoodRecipes] SET ARITHABORT OFF 
GO
ALTER DATABASE [FoodRecipes] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [FoodRecipes] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FoodRecipes] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FoodRecipes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FoodRecipes] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FoodRecipes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FoodRecipes] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FoodRecipes] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FoodRecipes] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FoodRecipes] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FoodRecipes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FoodRecipes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FoodRecipes] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FoodRecipes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FoodRecipes] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FoodRecipes] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FoodRecipes] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FoodRecipes] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FoodRecipes] SET  MULTI_USER 
GO
ALTER DATABASE [FoodRecipes] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FoodRecipes] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FoodRecipes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FoodRecipes] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [FoodRecipes] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FoodRecipes] SET  READ_WRITE 
GO
